#ifndef PIN_REFERENCES_H
#define PIN_REFERENCES_H

#define INTERNAL_LED_PIN 2

#define PIN_MOTOR_L_IN1 18
#define PIN_MOTOR_R_IN1 19
#define PIN_MOTOR_L_IN2 21
#define PIN_MOTOR_R_IN2 22
#define PIN_MOTOR_L_ENA 13
#define PIN_MOTOR_R_ENA 14

#define PIN_ENCODER_L_CLK 23
#define PIN_ENCODER_R_CLK 25
#define PIN_ENCODER_L_DT 26
#define PIN_ENCODER_R_DT 27

#endif